stages:
  - train
  - test
  - build
  - deploy

train_model:
  stage: train
  image: python:3.11-slim
  script:
    - pip install -r requirements.txt
    - python src/train.py
  artifacts:
    paths:
      - models/
    when: always

test_api:
  stage: test
  image: python:3.11-slim
  needs: [train_model]
  script:
    - pip install -r requirements.txt
    - pip install -r requirements-dev.txt
    - python -m pytest tests/ -v

build_image:
  stage: build
  image: docker:24
  services:
    - docker:24-dind
  needs: [test_api]
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:latest
  only:
    - main

deploy:
  stage: deploy
  image: alpine:latest
  needs: [build_image]
  environment:
    name: production
    url: https://registry.gitlab.com/Josephgit2025/mlops-spam-detector
  script:
    - echo "Image deployée sur le registry GitLab"
    - echo "Image disponible à $CI_REGISTRY_IMAGE:latest"
  only:
    - main