apiVersion: apps/v1
kind: Deployment
metadata:
  name: spam-detector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spam-detector
  template:
    metadata:
      labels:
        app: spam-detector
    spec:
      containers:
        - name: spam-detector
          image: josephmariebile/spam-detector:dacb2853d9a9fe88977f1a0f9fdc02ecbb8ec205
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: spam-detector-config
