name: CI/CD MLOps Spam Detector

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Installer les dépendances
        run: |
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: Entraîner le modèle pour les tests
        run: python src/train.py
        env:
          MLFLOW_TRACKING_URI: ""
      - name: Lancer les tests
        run: python -m pytest tests/ -v

  build:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Login Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build et Push image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            josephmariebile/spam-detector:latest
            josephmariebile/spam-detector:${{ github.sha }}
  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true
      - name: Mettre à jour le tag image
        run: |
          sed -i "s|image:.*spam-detector.*|image: josephmariebile/spam-detector:${{ github.sha }}|g" k8s/api/deployment.yaml
      - name: Commit et push
        run: |
          git config user.email "ci@github.com"
          git config user.name "GitHub Actions"
          git add k8s/api/deployment.yaml
          git commit -m "ci: update image tag to ${{ github.sha }}"
          git push